---
# tasks file for splunk

- name: Ensure Splunk is installed
  yum: name={{ splunk_files }}/splunk-{{ splunk_version }}.rpm state=present

- name: Ensure Splunk bindir is on the path
  copy: src=splunk.sh dest=/etc/profile.d/splunk.sh
        owner=root group=root mode=0644

- name: Ensure required Splunk users are present
  template: src=passwd.j2 dest=/opt/splunk/etc/passwd
            owner=splunk group=splunk mode=0600
  when: splunk_accts
  notify:
    - restart splunk

- name: Ensure Splunk is listening for forwarders
  template: src=inputs.conf.j2 dest=/opt/splunk/etc/system/local/inputs.conf
            owner={{ splunk_user }} group={{ splunk_group }}
  when: splunk_receiver | default(False)

- name: Ensure any required apps are installed
  unarchive: src={{ item.src }}
             dest={{ item.dest }}
             creates={{ item.dest }}/{{ item.creates }}
  when: item.state == 'present'
  with_items: splunk_apps
  notify:
    - restart splunk

- name: Ensure installed apps have correct file ownership
  file: path={{ item.dest }}/{{ item.creates }}
        recurse=true
        owner={{ splunk_user }} group={{ splunk_group }}
  with_items: splunk_apps
  when: item.state == 'present'
  notify:
    - restart splunk

- name: Remove any apps marked for deletion
  file: path={{ item.dest }}/{{ item.creates }}
        state=absent
  with_items: splunk_apps
  when: item.state == 'absent'
  notify:
    - restart splunk

- name: Ensure Splunk service is configured
  copy: src=splunk.init dest=/etc/init.d/splunk
        owner=root group=root mode=0755
  notify:
    - restart splunk

- name: Start Splunk service
  service: name=splunk state=started enabled=yes
